hk<-read.table("https://raw.githubusercontent.com/Shicheng-Guo/housekeeping/master/housekeeping.txt",head=T,sep="\t")
data<-read.csv("https://raw.githubusercontent.com/Shicheng-Guo/CCLE/master/extdata/ProteinRNACorrelation.txt",head=T,sep="\t")
head(data)
head(hk)
nrow(subset(data,Pearson<0))/nrow(data)
nrow(subset(data,Spearman<0))/nrow(data)
out<-data.frame(hk,data[match(hk$Gene_symbol,data$Gene.Symbol),])
head(out)
write.csv(out,file="housekeep.proteinRNAcorrelation.csv",quote=F,row.names = F)
getwd()
